Week5/W5D1/music_app/config/routes.rb
MusicApp::Application.routes.draw do
  resource :session, :only => [:new, :create, :destroy]
  
  resources :users do
    collection do
      get 'activate' #Should potentially be a put or post
    end
    put 'admin' #For creating admins
  end
  
  resources :bands do
    resources :albums, :only => [:index, :new, :create]
  end

  resources :albums, :except => [:index, :new, :create] do
    resources :tracks, :only => [:index, :new, :create]
  end
  
  resources :tracks, :except => [:index, :new, :create] do
    resources :notes, :only => [:create]
  end

  resources :notes, :only => [:destroy]

  root :to => 'bands#index'
end

Week5/W5D1/music_app/app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :name, :album_id, :track_type, :lyrics

  validates :name, :album_id, :presence => true

  belongs_to :album
  
  has_many :notes, :dependent => :destroy
end

Week5/W5D1/music_app/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_filter :logged_in?, :activated?
  before_filter :admin?, :except => [:index, :show]

  def index
    @album = Album.find(params[:album_id])
    @tracks = @album.tracks
  end

  def show
    @track = Track.find(params[:id])
    @note = Note.new
  end

  def new
    @track = Track.new(:album_id => params[:album_id])
    @albums = Album.all
  end

  def create
    @track = Track.new(params[:track])
    if @track.save
      redirect_to @track
    else
      @albums = Album.all
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def edit
    @track = Track.find(params[:id])
    @albums = Album.all
  end

  def update
    @track = Track.find(params[:id])
    if @track.update_attributes(params[:track])
      redirect_to @track
    else
      @albums = Album.all
      flash.now[:errors] = @track.errors.full_messages
      render :edit
    end
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy
    redirect_to album_tracks_url(@track.album_id)
  end
end

Week5/W5D1/music_app/app/helpers/tracks_helper.rb
module TracksHelper
  def show_lyrics(lyrics)
    m_lyrics = h(lyrics).split("\r\n")
    html = "<ul id=\"lyrics\">"
    m_lyrics.each do |lyric|
      html += "<li> "
      html += lyric
      html += "</li>"
    end
    html += "</ul>"
    html.html_safe
  end
end

Week5/W5D1/music_app/app/views/tracks/_form.html.erb
<input type="hidden" name="authenticity_token"
       value="<%= form_authenticity_token %>">

<label for="track_name">Name</label>
<input type="text" name="track[name]" value="<%= track.name %>"
       id="track_name">
</br>

<label for="track_album">Album</label>
<select name="track[album_id]" id="track_album">
  <% albums.each do |album| %>
    <option value="<%= album.id %>"
            <%= "selected" if track.album_id == album.id %>>
      <%= album.name %>
    </option>
  <% end %>
</select>
</br>

<label for="track_type">Type</label>
<input type="radio" name="track[track_type]" value="regular"
       id="track_type_regular">
<label for="track_type_regular">Regular Track</label>
<input type="radio" name="track[track_type]" value="bonus"
       id="track_type_bonus">
<label for="track_type_bonus">Bonus Track</label>
</br>

<p>Lyrics</p>
<textarea name="track[lyrics]" rows="10" cols="20">
  <%= track.lyrics %>
</textarea>
</br>

Week5/W5D1/music_app/app/views/tracks/edit.html.erb
<h1>Update Track</h1>
<form action="<%= track_url(@track) %>" method="post">
  <input type="hidden" name="_method" value="put">

  <%= render 'form', :track => @track, :albums => @albums %>

  <input type="submit" value="Update Track">
</form>

Week5/W5D1/music_app/app/views/tracks/index.html.erb
<h1><%= @album.name %>'s Tracks</h1>
<ul>
  <% @tracks.each do |track| %>
    <li><%= link_to track.name, track %></li>
  <% end %>
</ul>

<% if current_user.admin %>
  <%= link_to "Create a Track", new_album_track_url(@album) %>
<% end %>

Week5/W5D1/music_app/app/views/tracks/new.html.erb
<h1>Create Track</h1>
<form action="<%= album_tracks_url(@track.album_id) %>" method="post">

  <%= render 'form', :track => @track, :albums => @albums %>

  <input type="submit" value="Create Track">
</form>

Week5/W5D1/music_app/app/views/tracks/show.html.erb
<h1><%= @track.name %></h1>
<% if @track.track_type %>
  <p><%= @track.track_type.capitalize %> Track</p>
<% end %>

<h2>Band</h2>
<p><%= link_to @track.album.band.name,
               band_url(@track.album.band_id) %></p>

<h2>Album</h2>
<p><%= link_to @track.album.name, album_url(@track.album_id) %></p>

<h2>Lyrics</h2>
<%= show_lyrics(@track.lyrics) if @track.lyrics %>
</br>

<%= render 'notes/notes', :track => @track, :new_note => @note %>

<%= link_to "View all Tracks for this Album",
            album_tracks_url(@track.album_id) %>
<% if current_user.admin %>
 |
  <%= link_to "Edit this track", edit_track_url(@track) %>
<% end %>