Week4/W4D5/ninety_nine_cats/config/routes.rb
NinetyNineCats::Application.routes.draw do
  resource :user, :except => [:edit, :destroy] do
    collection do
      get 'edit'
    end
  end
  resource :session, :only => [:new, :create, :destroy] do
    collection do
      get 'see_request_possibilities'
    end
  end

  root :to => "cats#index"

  resources :cats
  resources :cat_rentals, :only => [:new, :create, :update] do
  	post "approve"
  	post "deny"
  end
end

Week4/W4D5/ninety_nine_cats/app/models/cat.rb
class Cat < ActiveRecord::Base
  GENDERS = ["M", "F"]

  attr_accessible :name, :age, :birth_date, :color, :gender

  validates_presence_of :name, :age, :birth_date, :color, :gender, :owner_id
  validates :gender, :inclusion => GENDERS
  validates :age, :numericality => true

  belongs_to :owner,
              :class_name => "User"

  has_many :rentals,
           :class_name => "CatRental"
end

Week4/W4D5/ninety_nine_cats/app/models/cat_rental.rb
class CatRental < ActiveRecord::Base
  attr_accessible :cat_id, :start_date, :end_date

  validates_presence_of :cat_id, :start_date, :end_date
  validate :start_date_is_before_end_date, :non_overlapping_request

  belongs_to :cat, :dependent => :destroy

  def approve!
    raise "request not pending" unless self.status == "PENDING"

    transaction do
      self.status = "APPROVED"
      self.save!
    
      overlapping_pending_requests.each do |request|
        request.status = "DENIED"
        request.save
      end
    end
  end

  def deny!
    self.status = "DENIED"
    self.save!
  end

  private

    def start_date_is_before_end_date
      if start_date > end_date
        error[:start_date] << "Start date cannot be before end date!"
      end
    end

    def overlapping_requests
      date_range = (start_date..end_date)
      CatRental.find_by_sql(
        [<<-SQL, date_range, date_range, cat_id, id])
        SELECT *
        FROM cat_rentals
        WHERE (start_date IN (?)
          OR end_date IN (?))
          AND cat_id = ?
          AND id != ?
          AND status != "DENIED"
      SQL
    end

    def overlapping_approved_requests
      overlapping_requests.select do |rental|
        rental.status == 'APPROVED'
      end
    end

    def overlapping_pending_requests
      overlapping_requests.select do |rental|
        rental.status == 'PENDING'
      end
    end

    def non_overlapping_request
      unless overlapping_approved_requests.empty? ||
            status == "DENIED"
        errors[:start_date] << "You can't make a request that conflicts with an already confirmed request."
      end
    end
end

Week4/W4D5/ninety_nine_cats/app/models/session_token.rb
class SessionToken < ActiveRecord::Base
  # attr_accessible :title, :body

  #set :ip in controller and pass as parameter via request.remote_ip and @session_token.ip = request.remote_ip
end

Week4/W4D5/ninety_nine_cats/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password

  validates_presence_of :username, :password_digest, :session_token


  has_many :cats,
           :foreign_key => :owner_id

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return user if !!user && user.is_password?(password)
    nil
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def password=(raw_password)
    self.password_digest = BCrypt::Password.create(raw_password)
  end

  def is_password?(pass)
    p = BCrypt::Password.new(self.password_digest)
    p.is_password?(pass)
  end
end

Week4/W4D5/ninety_nine_cats/app/controllers/cat_rentals_controller.rb
class CatRentalsController < ApplicationController
  before_filter :logged_in?
  before_filter :logged_in_as_owner?, :only => [:approve, :deny]

  def new
    @cat_rental = CatRental.new
    @cats = Cat.all
  end

  def create
    @cat_rental = CatRental.new(params[:cat_rental])
    if @cat_rental.save
      redirect_to cat_url(@cat_rental.cat_id)
    else
      @cats = Cat.all
      p @cats
      render :new
    end
  end

  def approve
    @cat_rental = CatRental.find(params[:cat_rental_id])
    @cat_rental.approve!
    redirect_to cat_url(@cat_rental.cat_id)
  end

  def deny
    @cat_rental = CatRental.find(params[:cat_rental_id])
    @cat_rental.deny!
    redirect_to cat_url(@cat_rental.cat_id)
  end

  private

    def logged_in_as_owner?
      @cat_rental = CatRental.find(params[:cat_rental_id])
      @cat = @cat_rental.cat
      unless current_user.id == @cat.owner_id
        redirect_to root_url
      end
    end
end

Week4/W4D5/ninety_nine_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_filter :logged_in?
  before_filter :logged_in_as_owner?, :only => [:edit, :update]

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(params[:cat])
    @cat.owner_id = current_user.id
    if @cat.save
      redirect_to cats_url
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @cat.update_attributes(params[:cat])
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  private

    def logged_in_as_owner?
      @cat = Cat.find(params[:id])
      unless current_user.id == @cat.owner_id
        redirect_to root_url
      end
    end
end

Week4/W4D5/ninety_nine_cats/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username],
                                     params[:user][:password])
    if !!@user
      login_user!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = ["Invalid username or password (or both)"]
      @user = User.new
      render :new
    end
  end

  def destroy
    @user = current_user
    logout_user!(@user) if !!@user
    redirect_to new_session_url
  end

  def see_request_possibilities
    render :json => request.env["HTTP_USER_AGENT"]
  end
end

Week4/W4D5/ninety_nine_cats/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :logged_in?, :only => [:edit, :update]

  def show
    @cats = current_user.cats
    render 'cats/index.html'
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.reset_session_token!
    if @user.save!
      login_user!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.is_password?(params[:user][:password])
      @user.password = params[:user][:new_password]
      if @user.save
        redirect_to user_url(@user)
      else
        flash.now[:errors] = @user.errors.full_messages
        render :edit
      end
    else
      flash.now[:errors] = "This is not your password!"
      render :edit
    end
  end
end

Week4/W4D5/ninety_nine_cats/app/helpers/sessions_helper.rb
module SessionsHelper
  def login_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout_user!(user)
    user.reset_session_token!
    session[:session_token] = nil
  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    redirect_to new_session_url if !current_user
  end
end

Week4/W4D5/ninety_nine_cats/app/views/cats/_form.html.erb
<input type="hidden" name="authenticity_token"
       value="<%= form_authenticity_token %>">

<label for="cat_name">Name:</label>
<input type="text" id="cat_name" name="cat[name]" value="<%= @cat.name %>">
</br>

<label for="cat_birth_date">
	Birthdate:
</label>
<input type="date" id="cat_birth_date" name="cat[birth_date]" value="<%= @cat.birth_date %>">
</br>


<label for="cat_age">
	Age:
</label>
<input type="text" id="cat_age" name="cat[age]" value="<%= @cat.age %>">
</br>

<label for="cat_color">
	Color:
</label>
<select name="cat[color]" id="cat_color">
  <option value=""></option>
  <option value="brown" <%= "selected" if @cat.color == "brown" %>>Brown</option>
  <option value="black" <%= "selected" if @cat.color == "black" %>>Black</option>
  <option value="white" <%= "selected" if @cat.color == "white" %>>
  	White
  </option>
  <option value="grey" <%= "selected" if @cat.color == "grey" %>>
  	Grey
  </option>
  <option value="orange" <%= "selected" if @cat.color == "orange" %>>
  	Orange
  </option>
</select>
</br>

<label for="cat_gender">
	Gender:
</label>
</br>
<input type="radio" id="cat_gender_male" name="cat[gender]" value="M" <%= 'checked' if @cat.gender == "M" %>>
<label for="cat_gender_male">
	Male
</label>
</br>

<input type="radio" id="cat_gender_female" name="cat[gender]" value="F" <%= "checked" if @cat.gender == "F" %>>
<label for="cat_gender_female">
	Female
</label>
</br>

Week4/W4D5/ninety_nine_cats/app/views/cats/_rental.html.erb
<li>Start Date: <%= rental.start_date %>,
  End Date <%= rental.end_date %>
  <% if rental.status == "PENDING" %>
    <% if rental.status == "PENDING" && current_user.id == cat.id %>
      <%= button_to "Approve", cat_rental_approve_url(rental) %>
      <%= button_to "Deny", cat_rental_deny_url(rental) %>
    <% end %>
  <% end %>
</li>

Week4/W4D5/ninety_nine_cats/app/views/cats/edit.html.erb
<form action="<%= cat_url(@cat) %>" method="post">
  <input type="hidden" name="_method" value="put">
  
  <%= render 'form' %>

  <input type="submit" value="Update your cat!">
</form>

Week4/W4D5/ninety_nine_cats/app/views/cats/index.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Color</th>
    <th>Gender</th>
  </tr>
  <% @cats.each do |cat| %>
    <tr>
      <td><%= link_to cat.name, cat %></td>
      <td><%= cat.age %></td>
      <td><%= cat.color %></td>
      <td>
        <%= cat.gender == "M" ? "Male" : "Female" %>
      </td>
    </tr>
  <% end %>
</table>

<%= link_to 'Create a new cat!', new_cat_url %>

Week4/W4D5/ninety_nine_cats/app/views/cats/new.html.erb
<form action="<%= cats_url %>" method="post">
  <%= render 'form' %>

  <input type="submit" value="Create a new cat!">
</form>

Week4/W4D5/ninety_nine_cats/app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>
<h2>This cat was born on: <%= @cat.birth_date %></h2>

<ul>
  <li>Age: <%= @cat.age %></li>
  <li>Color: <%= @cat.color %></li>
  <li>Gender:
    <%= @cat.gender == "M" ? "Male" : "Female" %>
  </li>
</ul>

<h2>Requests for <%= @cat.name %>:</h2>
<ul>
  <% @cat.rentals.order("start_date").each do |rental| %>
    <% unless rental.status == "DENIED" %>
      <%= render 'rental', :rental => rental, :cat => @cat %>
    <% end %>
  <% end %>
</ul>

<%= button_to "Rent #{@cat.name}", new_cat_rental_url, :method => :get %>
</br>

<%= link_to '99 Cats Home', root_url %>
<%= link_to "Edit #{@cat.name}", edit_cat_url(@cat) %>